import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Daniels SMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-4xl text-green-600">Hey Danny!</p>
      </main>
    </>
  );
}
